#!/usr/bin/env bash

#xdotool getactivewindow windowsize 448 413 windowmove 732 331

hc() { "${herbstclient_command[@]:-herbstclient}" "$@" ;}
dm() {
    rofi -dmenu "$@"
}
dmenu_lines=${dmenu_lines:-5}

case "$1" in

    *)
        # bring the selected window to the current tag and focus it
        name='Hidden'
        action() { hc bring "$@" ; }
        ;;
esac

id=$(herbstclient try foreach C clients. sprintf ATTR_V '%c.minimized' C and , compare ATTR_V = true , sprintf ATTR_TITLE '%c.title' C substitute TITLE ATTR_TITLE echo C TITLE | cut -d'.' -f2- | grep -v 'wselect.sh' | cat -n | sed 's/\t/) /g'| sed 's/^[ ]*//' \
    | dm -i -p "$name") \
    && action "$(awk '{ print $2 ; }' <<< "$id")"
