#!/usr/bin/env bash
# frames control menu

set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$SCRIPT_DIR/config"

declare options=("enable
disable")

choice=$(echo -e "${options[@]}" | ${DMENU} -i -p ' Main menu: ')

case "$choice" in
enable)
	choice="$SCRIPT_DIR/frames/enable"
	;;
disable)
	choice="$SCRIPT_DIR/frames/disable"
	;;
esac
sh "$choice"
