#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$SCRIPT_DIR/../scripts/config"

function main() {
  workspace=$(swaymsg -t get_workspaces | jq '.[].name' | tr -d \" | ${DMENU} -i -l 10 -p "Switch to workspace: ")
  swaymsg workspace $workspace
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
