#!/usr/bin/env bash
# shellcheck disable=SC2034
# Defined variables, modify anything in quotes to your prefered software
bg=$(xrdb -query | grep '*.background' | cut -f2- -d'#')
fg=$(xrdb -query | grep '*.foreground' | cut -f2- -d'#')

# DMENU="dmenu -nb #${bg} -nf #${fg} -sf #${bg} -sb #${fg} -fn Iosevka"
DMENU="rofi -dmenu"
DMBROWSER="firefox"
DMTERM="alacritty -e"
DMEDITOR="emacsclient -c -a emacs"

# wallpaper
setbg_dir="${HOME}/Pictures/Wallpapers"

# confedit
confedit_editor="$DMEDITOR"
declare -A confedit_list
confedit_list[confedit]="$HOME/.nixos-config/config/scripts/config"
confedit_list[colors]="$HOME/.nixos-config/modules/theme/colors.nix"
confedit_list[theme]="$HOME/.nixos-config/modules/theme/default.nix"
confedit_list[extended]="$HOME/.nixos-config/extended.nix"
confedit_list[alacritty]="$HOME/.nixos-config/modules/alacritty/default.nix"
confedit_list[doom emacs config.el]="$HOME/.doom.d/config.el"
confedit_list[doom emacs init.el]="$HOME/.doom.d/init.el"
confedit_list[doom emacs packages.el]="$HOME/.doom.d/packages.el"
confedit_list[dunst]="$HOME/.nixos-config/modules/dunst/default.nix"
confedit_list[herbstluftwm]="$HOME/.nixos-config/config/herbstluftwm/autostart"
confedit_list[neovim]="$HOME/.config/home/config/nvim/init.lua"
confedit_list[picom]="$HOME/.nixos-config/modules/picom/default.nix"
confedit_list[polybar]="$HOME/.nixos-config/config/polybar/config.ini"
confedit_list[system]="$HOME/.nixos-config/hosts/teishi/default.nix"
confedit_list[xmobar]="$HOME/.nixos-config/config/xmonad/xmobar.hs"
confedit_list[xmonad]="$HOME/.nixos-config/config/xmonad/xmonad.hs"
confedit_list[zathura]="$HOME/.nixos-config/modules/zathura/default.nix"

# Search engine config
websearch_browser="$DMBROWSER"
declare -A websearch

# Search Engines
websearch[duckduckgo]="https://duckduckgo.com/?q="
websearch[google]="https://www.google.com/search?q="
# Information/News
websearch[wikipedia]="https://en.wikipedia.org/w/index.php?search="
# Social Media
websearch[reddit]="https://www.reddit.com/search/?q="
websearch[youtube]="https://www.youtube.com/results?search_query="
# Development
websearch[github]="https://github.com/search?q="

# youtube config
declare -A youtube_channels
youtube_channels[DistroTube]="https://www.youtube.com/c/DistroTube/featured"
youtube_channels[System Crafters]="https://www.youtube.com/c/SystemCrafters/videos"
youtube_channels[Tim Ferriss]="https://www.youtube.com/c/timferriss/videos"
youtube_channels[Nick Cave]="https://www.youtube.com/c/nickcave/videos"

# translate config
# Uncomment to manually set the languages dm-translate will show
# Get language codes from here: https://github.com/TheDavidDelta/lingva-translate/blob/main/utils/languages.json
#translate_list="manual"
#declare -A lang_map
# lang_map[English]=en
# lang_map[Swedish]=sv
# lang_map[Automatic]=auto

_revision=17
