#!/usr/bin/env bash
#
# Script name: dm-hub
# Description: a hub that you can execute all the other scripts from
# Dependencies: dmenu, executable dmscripts, all the dependancies from dmscripts
# GitLab: https://www.gitlab.com/dwt1/hub
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: n-e0
#               Simon Ingelsson

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$SCRIPT_DIR/config"

function main() {
    local _self
    declare -A _scripts

    _self=$(basename "$0")

    while IFS= read -r -d '' script; do
        script_name="$(basename "${script}")"
        [[ "${script_name}" == "${_self}" ]] && continue
        [[ "${script_name}" == "config" ]] && continue
        _scripts[${script_name}]="${script}"
    done< <(find $SCRIPT_DIR -maxdepth 1 -type f -print0)

    choice=$(printf '%s\n' "${!_scripts[@]}" | sort | ${DMENU} -i -l 8 -p 'Run script' "$@")

    if [ "${choice}" ]; then
        bash "$(printf '%s\n' "${_scripts["${choice}"]}")" "$@"
    else
        echo "Program terminated." && exit 0
    fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
