#!/usr/bin/env bash

bg=$(cat ~/.Xresources | grep '*.background' | awk '{print $NF}')
fg=$(cat ~/.Xresources | grep '*.foreground' | awk '{print $NF}')

bemenu-run -c -M 600 --fn 'JuliaMono 12' -p 'Run:' -l 8 --tb ${bg} --tf ${fg} --fb ${bg} --ff ${fg} --nb ${bg} --nf ${fg} --sf ${bg} --sb ${fg} --hb ${fg} --hf ${bg}
