#!/usr/bin/env bash
# hlwm-utils main manu

set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$SCRIPT_DIR/utils/config"

declare options=("layouts
frames")

choice=$(echo -e "${options[@]}" | ${DMENU} -i -p 'Herbstutils')

case "$choice" in
layouts)
	choice="$SCRIPT_DIR/utils/layouts_menu"
	;;
frames)
	choice="$SCRIPT_DIR/utils/frames_menu"
	;;
esac
sh "$choice"
