#!/usr/bin/env bash

# a window selection utility
# dependencies: wmctrl, awk,
#               dmenu with multiline support (command line flag -l)
bg=$(xrdb -query | grep '*.background' | cut -f2- -d'#')
fg=$(xrdb -query | grep '*.foreground' | cut -f2- -d'#')

hc() { ${herbstclient_command:-herbstclient} "$@" ;}
dm() { ${dmenu_command:-dmenu -nb "#${bg}" -nf "#${fg}" -sf "#${bg}" -sb "#${fg}" -fn 'Iosevka' "$@"} "$@" ;}
dmenu_lines=${dmenu_lines:-10}

case "$1" in

    *)
        # bring the selected window to the current tag and focus it
        name='Bring:'
        action() { hc bring "$@" ; }
        ;;

esac

#wmctrl -l |cat -n| sed 's/\t/) /g'| sed 's/^[ ]*//' \
id=$(hc foreach C clients. sprintf ATTR_V '%c.minimized' C and , compare ATTR_V != true , sprintf ATTR_TITLE '%c.title' C substitute TITLE ATTR_TITLE echo C TITLE | cut -d'.' -f2- | grep -v 'wselect' | cat -n | sed 's/\t/) /g'| sed 's/^[ ]*//' \
    | dm -i -l "$dmenu_lines" -p "$name") \
    && action "$(awk '{ print $2 ; }' <<< "$id")"
