#!/usr/bin/env bash

#### AUTOSTART ####
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
xargs xwallpaper --stretch < ~/.cache/wall
~/.nixos-config/config/polybar/launch.sh

#### BSPWM configuration ####
# workspaces
bspc monitor -d 1 2 3 4 5

# base
bspc config border_width                  2
bspc config window_gap                    5
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config split_ratio                   0.50

# monocle
bspc config single_monocle                true
bspc config gapless_monocle               true
bspc config borderless_monocle true

# focus
bspc config click_to_focus                true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config pointer_follows_monitor       true
bspc config pointer_follows_focus         false
bspc config directional_focus_tightness   low
bspc config history_aware_focus           true
bspc config ignore_ewmh_focus             true

# pointer
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bg=$(cat ~/.Xresources | grep '*.background' | awk '{print $NF}')
fg=$(cat ~/.Xresources | grep '*.foreground' | awk '{print $NF}')
gray=$(cat ~/.Xresources | grep color8 | awk '{print $NF}')
red=$(cat ~/.Xresources | grep color1 | awk '{print $NF}')

bspc config normal_border_color      "$bg"
bspc config active_border_color      "$bg"
bspc config focused_border_color     "$fg"
bspc config presel_feedback_color    "$gray"
bspc config urgent_border_color      "$red"

#### RULES
bspc rule -r '*'

bspc rule -a Skype state=floating center=on
bspc rule -a Sxiv state=floating center=on
bspc rule -a Peek state=floating center=on
bspc rule -a flameshot state=floating center=on
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

# Desktop rules
bspc rule -a Firefox desktop=1
bspc rule -a discord desktop=2
bspc rule -a Signal desktop=2
bspc rule -a mpv desktop=5
bspc rule -a Spotify desktop=5

# Scratchpads 
bspc rule -a 'Emacs:*:scratch' state=floating center=on
bspc rule -a '*:terrm' state=floating center=on rectangle=900x600+0+0
bspc rule -a '*:monitorr' state=floating center=on rectangle=1200x600+0+0
bspc rule -a '*:mixerr' state=floating center=on rectangle=1000x300+0+0
bspc rule -a '*:spotiff' state=floating center=on rectangle=1200x500+0+0
