#!/usr/bin/env bash
# hlwm-utils main manu

set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$SCRIPT_DIR/config"

declare options=("tall
dwindle
columns
none")

choice=$(echo -e "${options[@]}" | ${DMENU} -i -p ' Select layout: ')

case "$choice" in
dwindle)
	choice="$SCRIPT_DIR/layouts/dwindle"
	;;
tall)
	choice="$SCRIPT_DIR/layouts/tall"
	;;
columns)
	choice="$SCRIPT_DIR/layouts/columns"
	;;
reset)
	choice="$SCRIPT_DIR/layouts/none"
	;;
esac
sh "$choice"
