#!/usr/bin/env bash
# hlwm-utils main manu

set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$SCRIPT_DIR/config"

declare options=("tall
dwindle
columns
|
reset")

choice=$(echo -e "${options[@]}" | ${DMENU} -i -p ' Select layput: ')

case "$choice" in
dwindle)
	choice="$SCRIPT_DIR/layouts/dwindle"
	;;
tall)
	choice="$SCRIPT_DIR/layouts/tall"
	;;
columns)
	choice="$SCRIPT_DIR/layouts/vertical"
	;;
reset)
	choice="$SCRIPT_DIR/layouts/reset"
	;;
esac
sh "$choice"
