#!/usr/bin/env bash

# WM INDEPENDENT KEYBINDINGS

# make sxhkd reload its configuration files:
super + Escape
      pkill -USR1 -x sxhkd

# BSPWM HOTKEYS

# quit/restart bspwm
super + shift + r
      bspc wm -r

# close and kill
super + shift + c
      bspc node -c

# alternate between the tiled and monocle layout
super + f
      bspc desktop -l next

# send the newest marked node to the newest preselected node
super + v
      bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + Return
      bspc node -s biggest.local || bspc node -s next.local


# STATE/FLAGS

# set the window state
super + {t,ctrl + t, shift + f}
      bspc node -t ~{floating,pseudo_tiled,fullscreen}

# set the node flags
super + x; {m,l,s,p}
      bspc node -g {marked,locked,sticky,private}


# FOCUS/SWAP

# focus the node in the given direction
super + {h,j,k,l}
    bspc node -f {west,south,north,east} || bspc monitor -f {west,south,north,east}

super + shift + {h,j,k,l}
    bspc node -s {west,south,north,east} --follow || bspc node -m {west,south,north,east} --follow

# focus the next/previous node in the current desktop
super + {_,shift + } n
      bspc node -f {next,prev}.local.!hidden.window.!locked


# switch to last active {desktop,node}
{super,alt} + grave
	bspc {desktop,node} -f last

# focus next/previous node/desktop
{super,alt} + {_,shift +} Tab
	bspc {desktop,node} -f {next,prev}.local


# focus next monitor or sent node to it
super + {_,shift +} o
  bspc {monitor -f,node -m} {next,prev}

# focus the node marked as urgent
super + u
      bspc node -f newest.urgent

# focus the last node
super + shift + u
      bspc node -f last

# focus or send to the given desktop
super + {_,shift + }{1-9}
     bspc {desktop -f,node -d} '^{1-9}'

# focus or send to the given monitor
super + {_,shift + }{w,e}
      bspc {monitor -f,node -m} '^{1-2}'

# DYNAMIC WORKSPACES
super + y; a
      bash ~/.nixos-config/config/bspwm/scripts/add_workspace 

super + y; s
      bash ~/.nixos-config/config/bspwm/scripts/switch_workspace goto

super + y; m
      bash ~/.nixos-config/config/bspwm/scripts/switch_workspace move

super + y; r
      bash ~/.nixos-config/config/bspwm/scripts/rename_workspace

super + y; d
      bspc desktop -r

# PRESELECT

# preselect the direction
super + alt + {h,j,k,l}
      bspc node -p {west,south,north,east}

# preselect the ratio
super + alt + {1-9}
      bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + alt + space
      bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
      bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel


# MOVE/RESIZE
super + ctrl {h,j,k,l}
  bspc node -z {left -20 0 || bspc node -z right -20 0, \
                bottom 0 20 || bspc node -z top 0 20,\
                top 0 -20 || bspc node -z bottom 0 -20,\
                right 20 0 || bspc node -z left 20 0}

# rotate windows by certain amounts
super + r
      bspc node @parent -R 90

# Equalize/balance windows
super + equal; {e,b}
      bspc node @/ {-E,-B}

# move a floating window
super + {Left,Down,Up,Right}
      bspc node -v {-40 0,0 40,0 -40,40 0}

# toggle bar
super + b
    {polybar-msg cmd hide; bspc config -m focused top_padding 0, polybar-msg cmd show; bspc config -m focused top_padding 20}

# APPLICATION KEYBINDINGS (Super + Alt + Key)
super + shift + Return
      alacritty

super + alt + b
      firefox

super + alt + f
      alacritty -e nnn

super + alt + e
      emacsclient -a '' -c

# Scratchpads

super + s; t
      bash ~/.nixos-config/config/bspwm/scripts/scratchpad terrm "alacritty --class terrm"

super + s; v
      bash ~/.nixos-config/config/bspwm/scripts/scratchpad mixerr "alacritty --class mixerr -e pulsemixer"

super + s; m
      bash ~/.nixos-config/config/bspwm/scripts/scratchpad monitorr "alacritty --class monitorr -e htop"

super + s; s
      bash ~/.nixos-config/config/bspwm/scripts/scratchpad spotiff "alacritty --class spotiff -e ncspot"

super + s; e
      bash ~/.nixos-config/config/bspwm/scripts/scratchpad scratch "emacsclient -a '' --eval (open-scratch-frame)"

# Volume
XF86AudioMute
    pamixer -t

XF86Audio{Raise,Lower}Volume
    pamixer -{i,d} 10

shift + XF86Audio{Raise,Lower}Volume
    pamixer -{i,d} 10 --allow-boost

# Media
XF86AudioPlay
      playerctl --player=spotify,ncspot play-pause

XF86AudioNext
      playerctl --player=spotify,ncspot next

XF86AudioPrev
      playerctl --player=spotify,ncspot previous

# Brightness
XF86MonBrightness{Up,Down}
    xbacklight -{inc,dec} 10

# Screenshot
super + Insert
        flameshot screen -p ~/Pictures/Screenshots

super + shift + Insert
        flameshot gui

# Notifications
control + shift + backslash
        dunstctl set-paused toggle

# Scripts
super + p
      bash ~/.nixos-config/config/scripts/menu

super + shift + q
      bash ~/.nixos-config/config/scripts/exit

super + ctrl + q
      bash ~/.nixos-config/config/scripts/kill

super + ctrl + r
      bash ~/.nixos-config/config/scripts/configurations

super + apostrophe
      bash ~/.nixos-config/config/bspwm/scripts/windowcd

super + shift + apostrophe
      bash ~/.nixos-config/config/bspwm/scripts/window

# show hidden windows
super + ctrl + apostrophe
      bash ~/.nixos-config/config/bspwm/scripts/hidden_windows

super + F1
      bash ~/.nixos-config/config/scripts/man

super + F2
      bash ~/.nixos-config/config/scripts/websearch

super + F3
        echo $(sxiv -t -o ~/Pictures/Wallpapers) > /home/alternateved/.cache/wall; xargs xwallpaper --stretch < ~/.cache/wall

super + F4
      bash ~/.nixos-config/config/scripts/youtube

super + F5
      bash ~/.nixos-config/config/scripts/wifi
