#!/usr/bin/env bash

# WM INDEPENDENT KEYBINDINGS

# make sxhkd reload its configuration files:
super + Escape
      pkill -USR1 -x sxhkd

# BSPWM HOTKEYS

# quit/restart bspwm
super + shift + r
      bspc wm -r

# close and kill
super + shift + c
      bspc node -c

# alternate between the tiled and monocle layout
super + f
      bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
      bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + Return
      bspc node -s biggest.local || bspc node -s next.local


# STATE/FLAGS

# set the window state
super + {t,ctrl + t, shift + f}
      bspc node -t {\~floating, \~pseudo_tiled, \~fullscreen}

# set the node flags
super + x; {m,l,s,p}
      bspc node -g {marked,locked,sticky,private}


# FOCUS/SWAP

# focus the node in the given direction
super + {h,j,k,l}
    bspc node -f {west,south,north,east} || bspc monitor -f {west,south,north,east}

super + shift + {h,j,k,l}
    bspc node -s {west,south,north,east} --follow || bspc node -m {west,south,north,east} --follow

# focus the next/previous node in the current desktop
super + {_,shift + }n
      bspc node -f {next,prev}.local.!hidden.window.!locked

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
      bspc desktop -f {prev,next}

# Swap monitors
super + {less,greater}
	bspc monitor --focus {prev,next}

# focus the last node/desktop
super + {grave,Tab}
      bspc {node,desktop} -f last

# focus the node marked as urgent
super + u
      bspc node -f newest.urgent

# focus the older or newer node in the focus history
super + {o,i}
      bspc wm -h off; \
      bspc node {older,newer} -f; \
      bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1,2,3,4,5,6}
      bspc {desktop -f,node -d} '^{1,2,3,4,5,6}'
      # bspc {desktop -f,node -d} '^{1,4,2,5,6,3}'

# Swap the contents of two desktops
super + alt + {1-6}
	target={1,2,3,4,5,6}; \
	bspc node "@focused:/" -s "@^$target:/" \
	    || bspc node "@focused:/" -d "^$target" \
	    || bspc node "@^$two:/" -d focused

# focus or send to the given monitor
super + {_,shift + }{w,e}
      bspc {monitor -f,node -m} '^{1-2}'

# PRESELECT

# preselect the direction
super + alt + {h,j,k,l}
      bspc node -p {west,south,north,east}

# preselect the ratio
super + alt + {1-9}
      bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + alt + space
      bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
      bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel


# MOVE/RESIZE
super + ctrl {h,j,k,l}
  bspc node -z {left -20 0 || bspc node -z right -20 0, \
                bottom 0 20 || bspc node -z top 0 20,\
                top 0 -20 || bspc node -z bottom 0 -20,\
                right 20 0 || bspc node -z left 20 0}

# rotate windows by certain amounts
super + r
      bspc node @parent -R 90

# Equalize/balance windows
super + equal; {e,b}
      bspc node @/ {-E,-B}

# move a floating window
super + {Left,Down,Up,Right}
      bspc node -v {-40 0,0 40,0 -40,40 0}

# APPLICATION KEYBINDINGS (Super + Alt + Key)
super + shift + Return
      alacritty

super + alt + b
      firefox

super + alt + f
      alacritty -e nnn

super + alt + e
      emacsclient -a '' -c

# Floaters
super + {_,shift } + z
    "$HOME"/.config/bspwm/scripts/scratchpad.sh {switch-app,toggle-flag}

super + s; {t,v,m,s}
      alacritty --class {"terrm","mixerr" -e pulsemixer,"monitorr" -e htop,"spotiff" -e ncspot}

super + s; e
      emacsclient --eval '(open-scratch-frame)'

# Volume
XF86AudioMute
    pactl set-sink-mute @DEFAULT_SINK@ toggle

XF86Audio{Raise,Lower}Volume
    pactl set-sink-volume @DEFAULT_SINK@ {+,-}10%

# Media
XF86AudioPlay
      playerctl --player=spotify,ncspot play-pause

XF86AudioNext
      playerctl --player=spotify,ncspot next

XF86AudioPrev
      playerctl --player=spotify,ncspot previous

# Brightness
XF86MonBrightness{Up,Down}
    xbacklight -{inc,dec} 10

# Screenshot
super + Insert
        flameshot screen -p ~/Pictures/Screenshots

super + shift + Insert
        flameshot gui

# Notifications
control + shift + backslash
        dunstctl set-paused toggle

super + F3
        echo $(sxiv -t -o ~/Pictures/Wallpapers) > /home/alternateved/.cache/wall; xargs xwallpaper --stretch < ~/.cache/wall

# run program launcher
super + p
      bash ~/.nixos-config/config/scripts/menu

super + shift + q
      bash ~/.nixos-config/config/scripts/exit

super + ctrl + p
      bash ~/.nixos-config/config/scripts/hub

super + ctrl + q
      bash ~/.nixos-config/config/scripts/kill

super + ctrl + r
      bash ~/.nixos-config/config/scripts/configurations

# super + apostrophe
#       rofi -show windowcd

# super + shift + apostrophe
#       rofi -show window

