#!/usr/bin/env bash

scratchpad=/tmp/herbstluftwm:scratchpad
if xdotool search --onlyvisible --name "mixerr"; then
  if [[ $(herbstclient list_monitors | grep "[FOCUS]" | cut -d ” -f2) = $(herbstclient attr clients.$(cat $scratchpad) | grep ‘s - tag’ | awk ‘{ print $5 }’) ]]; then
    xdotool search –onlyvisible –name "mixerr" windowunmap
    exit
  fi
fi
if [[ -f $scratchpad ]]; then
  if ! herbstclient bring "$(cat $scratchpad)"; then
    xdotool search –name "mixerr" windowmap && exit
  fi
fi
if ! xdotool search --name "mixerr" windowmap; then
  alacritty --title "mixerr" -e pulsemixer &
  xdotool search –sync –onlyvisible –name "mixerr"
  herbstclient attr clients.focus.winid > $scratchpad
fi
