#!/usr/bin/env bash

scratchpad=/tmp/herbstluftwm:scratchpad
if xdotool search --onlyvisible --name "monitorr"; then
  if [[ $(herbstclient list_monitors | grep "[FOCUS]" | cut -d ” -f2) = $(herbstclient attr clients.$(cat $scratchpad) | grep ‘s - tag’ | awk ‘{ print $5 }’) ]]; then
    xdotool search –onlyvisible –name "monitorr" windowunmap
    exit
  fi
fi
if [[ -f $scratchpad ]]; then
  if ! herbstclient bring "$(cat $scratchpad)"; then
    xdotool search –name "monitorr" windowmap && exit
  fi
fi
if ! xdotool search --name "monitorr" windowmap; then
  alacritty --title "monitorr" -e htop &
  xdotool search –sync –onlyvisible –name "monitorr"
  herbstclient attr clients.focus.winid > $scratchpad
fi
