#!/usr/bin/env bash

set -euo pipefail
source "/home/alternateved/.nixos-config/home/config/scripts/config"

main() {
    # Running ps to get running processes and display in dmenu.
    selected="$(ps --user "$(id -u)" -F | \
                ${DMENU} -i -l 20 -p "Search for process to kill:" "$@" | \
                awk '{print $2" "$11}')";

    # Nested 'if' statements.  The outer 'if' statement is what to do
    # when we select one of the 'selected' options listed in dmenu.
    if [[ -n $selected ]]; then
        # Piping No/Yes into dmenu as a safety measure, in case you
        # select a process that you don't actually want killed.
        answer="$(echo -e "No\nYes" | ${DMENU} -i -p "Kill $selected?" "$@")"

        if [[ $answer == "Yes" ]]; then
            selpid="$(awk '{print $1}' <<< "$selected")";
            kill -9 "$selpid"
        echo "Process $selected has been killed." && exit 0
        fi

        if [[ $answer == "No" ]]; then
        echo "Program terminated." && exit 0
        fi
    fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
