#!/usr/bin/env bash

set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$SCRIPT_DIR/config"

main() {
    # Running ps to get running processes and display in dmenu.
    selected="$(ps --user "$(id -u)" -F | \
                ${DMENU} -i -l 20 -p "Search for process to kill:" "$@" | \
                awk '{print $2" "$11}')";

    # Nested 'if' statements.  The outer 'if' statement is what to do
    # when we select one of the 'selected' options listed in dmenu.
    if [[ -n $selected ]]; then
        selpid="$(awk '{print $1}' <<< "$selected")";
        kill -9 "$selpid"
        echo "Process $selected has been killed." && exit 0
    fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
