#!/usr/bin/env bash

set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$SCRIPT_DIR/../../scripts/config"

function main() {
  workspace=$(echo "" | ${DMENU} -p "Rename workspace: ")
  bspc desktop -n $workspace
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
