#!/usr/bin/env bash

set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$SCRIPT_DIR/../../scripts/config"

ids=($(bspc query -N -n .local.window.!hidden))
options="$(<<< "${ids[@]}" xargs -r xtitle | awk '{ print ++i": "$0 }')"

[[ -n "$options" ]] || exit

id_index="$(<<< "$options" ${DMENU} -i -l 10 -p "Raise window:" | cut -d: -f1)"
bspc node "${ids[$((id_index - 1))]}" -f
